package frame.login;

import connection.MainConnection;
import frame.background_processing.WindowAction;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PREDATOR
 */
public class Create_Account_User extends WindowAction {

    static Connection connection = MainConnection.getConnection();
    static boolean isUsernameValid, isPasswordValid, isConfirmPasswordValid;

    /**
     * Creates new form Create_Account_User
     */
    public Create_Account_User() {
        initComponents();
    }

    public ResultSet queryResults() throws SQLException {
        PreparedStatement preparedStatement = connection.prepareStatement("select Username, Fullname, Age, Gender, Address, Tel, Password from Users");
        ResultSet resultSet = preparedStatement.executeQuery();

        return resultSet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbLogoCrimeFile = new javax.swing.JLabel();
        lbLogoCreateAccount = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbConfirmPassword = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbNumberPhone = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtFullName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtNumberPhone = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnReturn = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lbGender = new javax.swing.JLabel();
        cbbGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create User Account");

        panel.setBackground(new java.awt.Color(220, 220, 220));
        panel.setPreferredSize(new java.awt.Dimension(1080, 660));

        lbLogoCrimeFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbLogoCreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_create_account.png"))); // NOI18N

        lbFullName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbFullName.setText("Fullname ");

        lbUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbUsername.setText("Username");

        lbPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbPassword.setText("Password");

        lbConfirmPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbConfirmPassword.setText("Confirm password");

        lbAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbAddress.setText("Address");

        lbNumberPhone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNumberPhone.setText("Number phone");

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        txtConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFocusLost(evt);
            }
        });

        txtFullName.setBackground(new java.awt.Color(204, 204, 204));

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));

        txtUsername.setBackground(new java.awt.Color(204, 204, 204));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        txtNumberPhone.setBackground(new java.awt.Color(204, 204, 204));

        btnRegister.setBackground(new java.awt.Color(204, 255, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/register_button.png"))); // NOI18N
        btnRegister.setPreferredSize(new java.awt.Dimension(121, 32));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/reset_button.png"))); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(105, 32));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/btn_return.png"))); // NOI18N
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });

        lbAge.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbAge.setText("Age");

        txtAge.setBackground(new java.awt.Color(204, 204, 204));

        lbGender.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbGender.setText("Gender");

        cbbGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male\t", "Female" }));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogoCrimeFile))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(lbLogoCreateAccount))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbFullName)
                                .addGap(92, 92, 92)
                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                            .addComponent(lbNumberPhone)
                                            .addGap(48, 48, 48))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                            .addComponent(lbConfirmPassword)
                                            .addGap(18, 18, 18)))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbAddress)
                                            .addComponent(lbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUsername)
                                    .addComponent(lbGender)
                                    .addComponent(lbAge))
                                .addGap(88, 88, 88)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogoCrimeFile)
                    .addComponent(btnReturn))
                .addGap(59, 59, 59)
                .addComponent(lbLogoCreateAccount)
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAge)
                    .addComponent(txtAge))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGender)
                    .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumberPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        setVisible(false);
        JFrame frame = new Login_User();
        frame.setVisible(true);
    }//GEN-LAST:event_btnReturnMouseClicked

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        try {
            String usernameStr = txtUsername.getText();

            ResultSet resultSet = queryResults();
            while (resultSet.next()) {
                if (usernameStr.equalsIgnoreCase(resultSet.getString("Username"))) {
                    isUsernameValid = false;
                    JOptionPane.showMessageDialog(new Create_Account_User(), "Username already exist",
                            "Error", JOptionPane.ERROR_MESSAGE,
                            new ImageIcon(getClass().getResource("/images/logo/logo.png")));
                    txtUsername.requestFocus();
                } else 
                    isUsernameValid = true;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String passwordStr = new String(txtPassword.getPassword());
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$";

        if (!passwordStr.matches(passwordRegex)) {
            isPasswordValid = false;
            JOptionPane.showMessageDialog(this,
                    "Password length required more than 8 character,\nmust have at least one uppercase, lowercase, digit",
                    "Error", JOptionPane.ERROR_MESSAGE,
                    new ImageIcon(getClass().getResource("/images/logo/logo.png")));
            txtPassword.requestFocus();
        } else 
            isPasswordValid = true;
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFocusLost
        String passwordStr = new String(txtPassword.getPassword());
        String confirmPasswordStr = new String(txtConfirmPassword.getPassword());
        
        if (!passwordStr.equalsIgnoreCase(confirmPasswordStr)) {
            isConfirmPasswordValid = false;
            JOptionPane.showMessageDialog(this, "Confirm password don't match with password",
                    "Error", JOptionPane.ERROR_MESSAGE,
                    new ImageIcon(getClass().getResource("/images/logo/logo.png")));
            txtConfirmPassword.requestFocus();
        } else 
            isConfirmPasswordValid = true;
    }//GEN-LAST:event_txtConfirmPasswordFocusLost

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        JTextField[] arrTxt = {txtFullName, txtUsername, txtAge, txtPassword, 
            txtConfirmPassword, txtAddress, txtNumberPhone};
        
        List<JTextField> listTxt = new ArrayList<>();
        listTxt.addAll(Arrays.asList(arrTxt));
        
        boolean isEmpty = listTxt.stream().anyMatch(txt -> txt.getText().equalsIgnoreCase(""));
        if (isEmpty)
            JOptionPane.showMessageDialog(this, 
                    "All field must be filled in", "Error",
                    JOptionPane.ERROR_MESSAGE, 
                    new ImageIcon(getClass().getResource("/images/logo/logo.png")));
        if (isUsernameValid && isPasswordValid && isConfirmPasswordValid) {
            try {
                PreparedStatement preparedStatement = connection
                        .prepareStatement("insert Users values(?, ?, ?, ?, ?, ?, ?)");
                
                preparedStatement.setString(1, txtUsername.getText());
                preparedStatement.setString(2, txtFullName.getText());
                preparedStatement.setInt(3, Integer.parseInt(txtAge.getText()));
                
                // Handle for combo box 
                String gender = (cbbGender.getSelectedItem().toString()
                        .equalsIgnoreCase("Male")) ? "M" : "F";
                preparedStatement.setString(4, gender);
                
                preparedStatement.setString(5, txtAddress.getText());
                preparedStatement.setString(6, txtNumberPhone.getText());
                preparedStatement.setString(7, new String(txtPassword.getPassword()));
                
                preparedStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, 
                        "Create account with username " + txtUsername.getText() + " successfully!",
                        "Create account successfully", JOptionPane.INFORMATION_MESSAGE, 
                        new ImageIcon(getClass().getResource("/images/logo/logo.png")));
                
                setVisible(false);
                JFrame frame = new Login_User();
                frame.setVisible(true);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        JTextField[] arrTxt = {txtFullName, txtUsername, txtAge, txtPassword, 
            txtConfirmPassword, txtAddress, txtNumberPhone};
        
        List<JTextField> listTxt = new ArrayList<>();
        listTxt.addAll(Arrays.asList(arrTxt));
        
        listTxt.forEach(txt -> txt.setText(""));
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Account_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Account_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JComboBox<String> cbbGender;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbConfirmPassword;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbLogoCreateAccount;
    private javax.swing.JLabel lbLogoCrimeFile;
    private javax.swing.JLabel lbNumberPhone;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtNumberPhone;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
