/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.crime;

import connection.MainConnection;
import frame.background_processing.WindowAction;
import frame.home.Home_Admin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import object.Crime;

/**
 *
 * @author user
 */
public class Crime_Manage extends WindowAction {

    public static final ArrayList<Crime> arrCrime = new ArrayList<Crime>();
    public static final Connection connCrimeFile = MainConnection.getConnection();

    /**
     * Creates new form Crime_Manage
     */
    public Crime_Manage() {
        dataArrayListFromCrime();
        initComponents();
        loadDataArrayListToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbRegisterComplaint = new javax.swing.JLabel();
        scrollPaneCrime = new javax.swing.JScrollPane();
        tableCrime = new javax.swing.JTable();
        panelControlCrime = new javax.swing.JPanel();
        lbControlCrime = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbOccupation = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        cbbGender = new javax.swing.JComboBox<>();
        txtOccupation = new javax.swing.JTextField();
        cbbType = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnReturn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Manage Crime");

        panel.setBackground(new java.awt.Color(220, 220, 220));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbRegisterComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_crime.png"))); // NOI18N

        tableCrime.setBackground(new java.awt.Color(204, 204, 204));
        tableCrime.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableCrime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crime ID", "Full Name", "Age", "Gender", "Occupation", "Type of crime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableCrime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCrimeMouseClicked(evt);
            }
        });
        scrollPaneCrime.setViewportView(tableCrime);

        panelControlCrime.setBackground(new java.awt.Color(204, 204, 204));

        lbControlCrime.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbControlCrime.setText("Control Crime");

        lbFullName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbFullName.setText("Full Name");

        lbAge.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbAge.setText("Age");

        lbGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbGender.setText("Gender");

        lbOccupation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbOccupation.setText("Occupation");

        lbType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbType.setText("Type of crime");

        txtFullname.setBackground(new java.awt.Color(215, 215, 215));
        txtFullname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullnameFocusLost(evt);
            }
        });

        txtAge.setBackground(new java.awt.Color(215, 215, 215));
        txtAge.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });

        cbbGender.setBackground(new java.awt.Color(215, 215, 215));
        cbbGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));

        txtOccupation.setBackground(new java.awt.Color(215, 215, 215));
        txtOccupation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtOccupation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOccupationFocusLost(evt);
            }
        });

        cbbType.setBackground(new java.awt.Color(215, 215, 215));
        cbbType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corruption", "Counterfeit Currency Or Documents", "Crimes Against Children", "Cyber Crime", "Drug Trafficking", "Environmental Crime", "Financial Crime\t", "Firearms Trafficking", "Human Trafficking", "Illcit Goods", "Killing Crime", "Kidnap Crime", " " }));

        btnReset.setBackground(new java.awt.Color(51, 51, 51));
        btnReset.setForeground(new java.awt.Color(51, 51, 51));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/reset_button.png"))); // NOI18N
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/delete-button.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 204, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/update_button.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(51, 153, 0));
        btnCreate.setForeground(new java.awt.Color(51, 153, 0));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/create-button.png"))); // NOI18N
        btnCreate.setMaximumSize(new java.awt.Dimension(95, 31));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelControlCrimeLayout = new javax.swing.GroupLayout(panelControlCrime);
        panelControlCrime.setLayout(panelControlCrimeLayout);
        panelControlCrimeLayout.setHorizontalGroup(
            panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlCrimeLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(lbControlCrime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelControlCrimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlCrimeLayout.createSequentialGroup()
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGender)
                            .addComponent(lbAge)
                            .addComponent(lbFullName))
                        .addGap(46, 46, 46)
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelControlCrimeLayout.createSequentialGroup()
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOccupation)
                            .addComponent(lbType))
                        .addGap(21, 21, 21)
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOccupation))))
                .addGap(18, 18, 18)
                .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panelControlCrimeLayout.setVerticalGroup(
            panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlCrimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbControlCrime)
                .addGap(27, 27, 27)
                .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlCrimeLayout.createSequentialGroup()
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbFullName)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAge))
                        .addGap(29, 29, 29)
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbGender)
                            .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbOccupation)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelControlCrimeLayout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(panelControlCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbType))
                .addGap(288, 288, 288))
        );

        txtSearch.setBackground(new java.awt.Color(245, 245, 245));
        txtSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/btn_return.png"))); // NOI18N
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(scrollPaneCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(panelControlCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 487, Short.MAX_VALUE))
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbRegisterComplaint)
                        .addGap(405, 405, 405))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo)
                    .addComponent(btnReturn))
                .addGap(98, 98, 98)
                .addComponent(lbRegisterComplaint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelControlCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String getNextCrimeID() throws SQLException {
        String nextCrimeID = "";

        Statement staCreateCrime = connCrimeFile.createStatement();
        ResultSet rsCreateCrime = staCreateCrime.executeQuery("SELECT MAX(CrimeID) AS MaxCrimeID FROM Crime");

        if (rsCreateCrime.next()) {
            String maxCrimeID = rsCreateCrime.getString("MaxCrimeID");
            if (maxCrimeID != null) {
                int numericPart = Integer.parseInt(maxCrimeID.substring(3));
                numericPart++;
                nextCrimeID = "Cri" + String.format("%03d", numericPart);
            } else {
                nextCrimeID = "Cri001";
            }
        }

        rsCreateCrime.close();
        staCreateCrime.close();

        return nextCrimeID;
    }
    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        int selectRow = tableCrime.getSelectedRow();

        String fullName = txtFullname.getText();
        String age = txtAge.getText();
        String genderStr = cbbGender.getSelectedItem().toString();
        char gender = genderStr.charAt(0);
        String Occupation = txtOccupation.getText();
        String type = cbbType.getSelectedItem().toString();

        try {
            String nextCrimeID = getNextCrimeID();

            PreparedStatement preUpdateCrime = connCrimeFile.prepareStatement("INSERT INTO Crime (CrimeID, Fullname, Age, Gender, Occupation, Type) VALUES (?,?,?,?,?,?)");
            preUpdateCrime.setString(1, nextCrimeID);
            preUpdateCrime.setString(2, fullName);
            preUpdateCrime.setString(3, age);
            preUpdateCrime.setString(4, String.valueOf(gender));
            preUpdateCrime.setString(5, Occupation);
            preUpdateCrime.setString(6, type);
            preUpdateCrime.executeUpdate();

            preUpdateCrime.close();
            JOptionPane.showMessageDialog(null, "Create successful", "Success", JOptionPane.INFORMATION_MESSAGE);
            dataArrayListFromCrime();
            loadDataArrayListToTable();
        } catch (SQLException ex) {
            System.out.println("Error create " + ex);
        }
    }//GEN-LAST:event_btnCreateMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        int confirmResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Confirm Update", JOptionPane.YES_NO_OPTION);

        if (confirmResult == JOptionPane.YES_OPTION) {
            int selectRow = tableCrime.getSelectedRow();

            String crimeID = tableCrime.getValueAt(selectRow, 0).toString();
            String fullName = txtFullname.getText();
            String age = txtAge.getText();
            String genderStr = cbbGender.getSelectedItem().toString();
            char gender = genderStr.charAt(0);
            String occupation = txtOccupation.getText();
            String type = cbbType.getSelectedItem().toString();

            try {
                PreparedStatement preUpdateCase = connCrimeFile.prepareStatement("Update Crime Set Fullname = ? , Age = ?, Gender = ?, Occupation = ?, Type = ?"
                               + " Where CrimeID = ?");
                preUpdateCase.setString(1, fullName);
                preUpdateCase.setString(2, age);
                preUpdateCase.setString(3, String.valueOf(gender));
                preUpdateCase.setString(4, occupation);
                preUpdateCase.setString(5, type);
                preUpdateCase.setString(6, crimeID);
                preUpdateCase.executeUpdate();

                preUpdateCase.close();
                JOptionPane.showMessageDialog(null, "Update successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                dataArrayListFromCrime();
                loadDataArrayListToTable();
            } catch (SQLException ex) {
                System.out.println("Error create " + ex);
            }
        }

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int rely = JOptionPane.showConfirmDialog(this, "You sure want to delete !", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (rely == JOptionPane.YES_OPTION) {
            String idColumnDelete;
            int rowDelete;
            rowDelete = tableCrime.getSelectedRow();
            idColumnDelete = (String) tableCrime.getValueAt(rowDelete, 0);
            System.out.println(" " + idColumnDelete);
            deleteRow(idColumnDelete);
            dataArrayListFromCrime();
            loadDataArrayListToTable();
            JOptionPane.showMessageDialog(this, "Successful Delete.");
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        txtFullname.setText("");
        txtAge.setText("");
        cbbGender.setSelectedItem("Male");
        txtOccupation.setText("");
        cbbType.setSelectedItem("Corruption");
    }//GEN-LAST:event_btnResetMouseClicked

    private void tableCrimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCrimeMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableCrime.getModel();
        int selectIndex = tableCrime.getSelectedRow();
        txtFullname.setText(model.getValueAt(selectIndex, 1).toString());
        txtAge.setText(model.getValueAt(selectIndex, 2).toString());
        cbbGender.setSelectedItem(model.getValueAt(selectIndex, 3).toString());
        txtOccupation.setText(model.getValueAt(selectIndex, 4).toString());
        cbbType.setSelectedItem(model.getValueAt(selectIndex, 5).toString());
    }//GEN-LAST:event_tableCrimeMouseClicked

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        arrCrime.clear();
        try {
            String searchEnter = txtSearch.getText();
            String sqlSearch = "SELECT CrimeID, Fullname, Age, Gender, Occupation, Type FROM Crime Where CrimeID Like ? Or Fullname Like ? "
                           + "Or Age Like ? Or Gender Or Occupation Like ? Or Type = ?";
            PreparedStatement preSearch = connCrimeFile.prepareStatement(sqlSearch);
            preSearch.setString(1, "%" + searchEnter + "%");
            preSearch.setString(2, "%" + searchEnter + "%");
            preSearch.setString(3, "%" + searchEnter + "%");
            preSearch.setString(4, "%" + searchEnter + "%");
            preSearch.setString(5, "%" + searchEnter + "%");
            preSearch.setString(6, "%" + searchEnter + "%");
            ResultSet rsCrime = preSearch.executeQuery();
            while (rsCrime.next()) {
                String crimeID = rsCrime.getString("CrimeID");
                String fullName = rsCrime.getString("Fullname");
                int age = rsCrime.getInt("Age");
                String genderStr = rsCrime.getString("Gender");
                char gender = genderStr.charAt(0);
                String occupation = rsCrime.getString("Occupation");
                String type = rsCrime.getString("Type");

                Crime crimeTable = new Crime(crimeID, fullName, age, gender, occupation, type);
                arrCrime.add(crimeTable);
            }
            loadDataArrayListToTable();
        } catch (SQLException e) {
            System.out.println("Error search " + e);
        }
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtFullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullnameFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fullname not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtFullnameFocusLost

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
        JTextField textField = (JTextField) evt.getSource();
        String age = textField.getText();
        if (age.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Age cannot be empty!");
            textField.requestFocus();
            return;
        }

        try {
            int ageValue = Integer.parseInt(age);
            if (ageValue < 1 || ageValue > 150) {
                JOptionPane.showMessageDialog(this, "Age must be a number between 1 and 150!");
                textField.setText("");
                textField.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a valid number!");
            textField.setText("");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtAgeFocusLost

    private void txtOccupationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOccupationFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Occupation not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtOccupationFocusLost

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        Home_Admin homeAdmin = new Home_Admin();
        homeAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crime_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crime_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crime_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crime_Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crime_Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbGender;
    private javax.swing.JComboBox<String> cbbType;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbControlCrime;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbOccupation;
    private javax.swing.JLabel lbRegisterComplaint;
    private javax.swing.JLabel lbType;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelControlCrime;
    private javax.swing.JScrollPane scrollPaneCrime;
    private static javax.swing.JTable tableCrime;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void dataArrayListFromCrime() {
        arrCrime.clear();
        try {
            Statement staCrime = connCrimeFile.createStatement();
            ResultSet rsCrime = staCrime.executeQuery("SELECT CrimeID, Fullname, Age, Gender, Occupation, Type FROM Crime");
            System.out.println("CrimeID\t Fullname\t Age\t Gender\t Occupation\t Type");
            while (rsCrime.next()) {
                String crimeID = rsCrime.getString("CrimeID");
                String fullName = rsCrime.getString("Fullname");
                int age = rsCrime.getInt("Age");
                String genderStr = rsCrime.getString("Gender");
                char gender = genderStr.charAt(0);
                String occupation = rsCrime.getString("Occupation");
                String type = rsCrime.getString("Type");

                Crime crimeTable = new Crime(crimeID, fullName, age, gender, occupation, type);
                arrCrime.add(crimeTable);
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving data from Crime: " + e);
        }
    }

    private void loadDataArrayListToTable() {
        DefaultTableModel model = (DefaultTableModel) Crime_Manage.tableCrime.getModel();
        model.setRowCount(0);

        for (Crime crime : arrCrime) {
            model.addRow(new Object[]{crime.getCrimeID(), crime.getfullName(), crime.getAge(), crime.getGender(), crime.getOccupation(), crime.getType()});
        }
    }

    private void deleteRow(String idColumnDelete) {
        int rows = 0;
        try {
            String sqlDelete = "Delete From Crime Where  CrimeID = ?";
            PreparedStatement preDelete = connCrimeFile.prepareStatement(sqlDelete);
            preDelete.setString(1, idColumnDelete);
            rows = preDelete.executeUpdate();
            if (rows >= 1) {
                System.out.println("Successful Delete");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed", "Notice", HEIGHT);
            }
            preDelete.close();
        } catch (SQLException e) {
            System.out.println("Error delete row " + e);
        }
    }
}
