/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.home;

import frame.background_processing.WindowAction;

/**
 *
 * @author PREDATOR
 */
public class Home_User extends WindowAction {

    /**
     * Creates new form Home_User
     */
    public Home_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbLogoCrimeFile = new javax.swing.JLabel();
        lbHome_User = new javax.swing.JLabel();
        btnRegisterComplaint = new javax.swing.JButton();
        btnViewComplaintStatus = new javax.swing.JButton();
        btnViewCaseHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User Home");

        panel.setBackground(new java.awt.Color(220, 220, 220));
        panel.setPreferredSize(new java.awt.Dimension(1080, 660));

        lbLogoCrimeFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbHome_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_user_account.png"))); // NOI18N

        btnRegisterComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/register_complaint_of_user_account.png"))); // NOI18N

        btnViewComplaintStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_view_complaint_status.png"))); // NOI18N
        btnViewComplaintStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplaintStatusActionPerformed(evt);
            }
        });

        btnViewCaseHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_view_complaint_status.png"))); // NOI18N
        btnViewCaseHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCaseHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(lbLogoCrimeFile)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(148, 148, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHome_User)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnRegisterComplaint)
                        .addGap(65, 65, 65)
                        .addComponent(btnViewComplaintStatus)))
                .addGap(77, 77, 77)
                .addComponent(btnViewCaseHistory)
                .addGap(205, 205, 205))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewCaseHistory)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lbLogoCrimeFile)
                        .addGap(99, 99, 99)
                        .addComponent(lbHome_User)
                        .addGap(78, 78, 78)
                        .addComponent(btnRegisterComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnViewComplaintStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(358, 358, 358))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewComplaintStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplaintStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewComplaintStatusActionPerformed

    private void btnViewCaseHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCaseHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCaseHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterComplaint;
    private javax.swing.JButton btnViewCaseHistory;
    private javax.swing.JButton btnViewComplaintStatus;
    private javax.swing.JLabel lbHome_User;
    private javax.swing.JLabel lbLogoCrimeFile;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
