/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.fir;

import frame.fir.Manage_Fir;
import frame.background_processing.WindowAction;
import frame.mainconnection.MainConnection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import object.Fir;

/**
 *
 * @author PREDATOR
 */
public class Manage_Fir extends WindowAction {

    public static final ArrayList<Fir> arrFir = new ArrayList<Fir>();
    public static final Connection connFir = MainConnection.getConnection();

    /**
     * Creates new form Manage_Fir
     */
    public Manage_Fir() {
        dataArrayListFromFir();
        initComponents();
        loadDataArrayListToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFir = new javax.swing.JTable();
        pnControlFIR = new javax.swing.JPanel();
        lbControlFIR = new javax.swing.JLabel();
        lbSuspectName = new javax.swing.JLabel();
        lbLocation = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        lbEvidence = new javax.swing.JLabel();
        lbDateOfOccurence = new javax.swing.JLabel();
        txtfLocation = new javax.swing.JTextField();
        txtfDescription = new javax.swing.JTextField();
        txtfSuspectName = new javax.swing.JTextField();
        txtfEvidence = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        cbDate = new javax.swing.JComboBox<>();
        cbMonth = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        lbLogo = new javax.swing.JLabel();
        lbLogoManageFIR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 660));

        txtfSearch.setText("Search ...");
        txtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSearchActionPerformed(evt);
            }
        });

        tbFir.setBackground(new java.awt.Color(204, 204, 204));
        tbFir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FIR ID", "Suspect Name", "Location", "Description", "Date Of Occurence", "Evidence", "Admin ID"
            }
        ));
        tbFir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFir);

        pnControlFIR.setBackground(new java.awt.Color(204, 204, 204));
        pnControlFIR.setPreferredSize(new java.awt.Dimension(1078, 239));

        lbControlFIR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbControlFIR.setText("Control FIR");

        lbSuspectName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbSuspectName.setText("Suspect Name");

        lbLocation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbLocation.setText("Location");

        lbDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDescription.setText("Description");

        lbEvidence.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbEvidence.setText("Evidence");

        lbDateOfOccurence.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDateOfOccurence.setText("Date Of Occurence");

        txtfLocation.setBackground(new java.awt.Color(220, 220, 220));
        txtfLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfLocationFocusLost(evt);
            }
        });

        txtfDescription.setBackground(new java.awt.Color(220, 220, 220));
        txtfDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfDescriptionFocusLost(evt);
            }
        });

        txtfSuspectName.setBackground(new java.awt.Color(220, 220, 220));
        txtfSuspectName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfSuspectNameFocusLost(evt);
            }
        });

        txtfEvidence.setBackground(new java.awt.Color(220, 220, 220));
        txtfEvidence.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfEvidenceFocusLost(evt);
            }
        });
        txtfEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEvidenceActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(51, 153, 0));
        btnCreate.setForeground(new java.awt.Color(51, 153, 0));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/create-button.png"))); // NOI18N
        btnCreate.setMaximumSize(new java.awt.Dimension(95, 31));
        btnCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 204, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/update_button.png"))); // NOI18N
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/delete-button.png"))); // NOI18N
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(51, 51, 51));
        btnReset.setForeground(new java.awt.Color(51, 51, 51));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/reset_button.png"))); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(100, 30));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cbDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnControlFIRLayout = new javax.swing.GroupLayout(pnControlFIR);
        pnControlFIR.setLayout(pnControlFIRLayout);
        pnControlFIRLayout.setHorizontalGroup(
            pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlFIRLayout.createSequentialGroup()
                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnControlFIRLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(lbControlFIR))
                    .addGroup(pnControlFIRLayout.createSequentialGroup()
                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnControlFIRLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLocation)
                                    .addComponent(lbDescription))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnControlFIRLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbSuspectName)
                                .addGap(18, 18, 18)))
                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfSuspectName, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtfDescription)
                            .addComponent(txtfLocation))
                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnControlFIRLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDateOfOccurence)
                                    .addComponent(lbEvidence))
                                .addGap(18, 18, 18)
                                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfEvidence, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnControlFIRLayout.createSequentialGroup()
                                        .addComponent(cbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnControlFIRLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        pnControlFIRLayout.setVerticalGroup(
            pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlFIRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControlFIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnControlFIRLayout.createSequentialGroup()
                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnControlFIRLayout.createSequentialGroup()
                                .addComponent(lbLocation)
                                .addGap(35, 35, 35)
                                .addComponent(lbDescription))
                            .addGroup(pnControlFIRLayout.createSequentialGroup()
                                .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEvidence)
                                    .addGroup(pnControlFIRLayout.createSequentialGroup()
                                        .addComponent(lbDateOfOccurence)
                                        .addGap(57, 57, 57))
                                    .addGroup(pnControlFIRLayout.createSequentialGroup()
                                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addComponent(txtfEvidence, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addComponent(txtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnControlFIRLayout.createSequentialGroup()
                        .addGroup(pnControlFIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSuspectName)
                            .addComponent(txtfSuspectName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnControlFIRLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbLogoManageFIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_fir.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbLogo)
                .addGap(201, 201, 201)
                .addComponent(lbLogoManageFIR)
                .addContainerGap(368, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnControlFIR, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLogo)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbLogoManageFIR)))
                .addGap(27, 27, 27)
                .addComponent(txtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnControlFIR, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSearchActionPerformed

    private void txtfEvidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEvidenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEvidenceActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbFirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFirMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbFir.getModel();
        int selectIndex = tbFir.getSelectedRow();
        txtfSuspectName.setText(model.getValueAt(selectIndex, 1).toString());
        txtfLocation.setText(model.getValueAt(selectIndex, 2).toString());
        txtfDescription.setText(model.getValueAt(selectIndex, 3).toString());
        txtfEvidence.setText(model.getValueAt(selectIndex, 5).toString());
    }//GEN-LAST:event_tbFirMouseClicked

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked

        String suspectName = txtfSuspectName.getText();
        String location = txtfLocation.getText();
        String description = txtfDescription.getText();
        String evidence = txtfEvidence.getText();

        String dayStr = cbDate.getSelectedItem().toString();
        String monthStr = cbMonth.getSelectedItem().toString();
        String yearStr = cbYear.getSelectedItem().toString();

        //parse string to int
        int day = Integer.parseInt(dayStr);
        int month = Integer.parseInt(monthStr);
        int year = Integer.parseInt(yearStr);

        //check date month
        LocalDate date = LocalDate.of(year, month, 1);
        if (day < 1 || day > date.lengthOfMonth()) {
            JOptionPane.showMessageDialog(null, "Date invalid", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        date = LocalDate.of(year, month, day);

        try {
            Statement staCreateFir = connFir.createStatement();
            ResultSet rsCreateFir = staCreateFir.executeQuery("SELECT TOP 1 FirID FROM FIR ORDER BY FirID DESC");

            int maxFirID = 0;
            if (rsCreateFir.next()) {
                String maxFirIDStr = rsCreateFir.getString("FirID");
                maxFirID = Integer.parseInt(maxFirIDStr.substring(3));
            }

            String nextFirID = "Fir" + String.format("%03d", maxFirID + 1);

            PreparedStatement preCreateFir = connFir.prepareStatement("INSERT INTO FIR (FirID, SuspectName, Location, Description, DateOfOccurence, Evidence) VALUES (?,?,?,?,?,?)");
            preCreateFir.setString(1, nextFirID);
            preCreateFir.setString(2, suspectName);
            preCreateFir.setString(3, location);
            preCreateFir.setString(4, description);
            preCreateFir.setDate(5, java.sql.Date.valueOf(date));
            preCreateFir.setString(6, evidence);
            preCreateFir.executeUpdate();

            connFir.close();
        } catch (SQLException ex) {
            System.out.println("Error create " + ex);
        }
    }//GEN-LAST:event_btnCreateMouseClicked

    private void txtfSuspectNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfSuspectNameFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "SuspectName not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtfSuspectNameFocusLost

    private void txtfLocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfLocationFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Location not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtfLocationFocusLost

    private void txtfDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfDescriptionFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtfDescriptionFocusLost

    private void txtfEvidenceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfEvidenceFocusLost
        JTextField textField = (JTextField) evt.getSource();
        if (textField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Evidence not empty !");
            textField.requestFocus();
        }
    }//GEN-LAST:event_txtfEvidenceFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Fir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Fir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private static javax.swing.JComboBox<String> cbDate;
    private static javax.swing.JComboBox<String> cbMonth;
    private static javax.swing.JComboBox<String> cbYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbControlFIR;
    private javax.swing.JLabel lbDateOfOccurence;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbEvidence;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogoManageFIR;
    private javax.swing.JLabel lbSuspectName;
    private javax.swing.JPanel pnControlFIR;
    private static javax.swing.JTable tbFir;
    private javax.swing.JTextField txtfDescription;
    private javax.swing.JTextField txtfEvidence;
    private javax.swing.JTextField txtfLocation;
    private javax.swing.JTextField txtfSearch;
    private javax.swing.JTextField txtfSuspectName;
    // End of variables declaration//GEN-END:variables

    private void dataArrayListFromFir() {
        arrFir.clear();
        try {
            Statement staFir = connFir.createStatement();
            ResultSet rsFir = staFir.executeQuery("SELECT FirID, SuspectName, Location, Description, DateOfOccurence, Evidence, AdminID FROM FIR");
            System.out.println("FirID\tSuspectName\tLocation\tDescription\tDateOfOccurence\tEvidence\tAdminID");
            while (rsFir.next()) {
                String firID = rsFir.getString("FirID");
                String suspectName = rsFir.getString("SuspectName");
                String location = rsFir.getString("Location");
                String description = rsFir.getString("Description");
                Date dateOfOccurence = rsFir.getDate("DateOfOccurence");
                String evidence = rsFir.getString("Evidence");
                String adminID = rsFir.getString("AdminID");

                Fir firTable = new Fir(firID, suspectName, location, description, dateOfOccurence, evidence, adminID);
                arrFir.add(firTable);
            }
        } catch (SQLException e) {
            System.out.println("Error retrieving data from FIR: " + e);
        }
    }

    private void loadDataArrayListToTable() {
        DefaultTableModel model = (DefaultTableModel) Manage_Fir.tbFir.getModel();
        model.setRowCount(0);

        for (Fir fir : arrFir) {
            model.addRow(new Object[]{fir.getFirID(), fir.getSuspectName(), fir.getLocation(), fir.getDescription(), fir.getDateofOccurence(), fir.getEvidence(), fir.getAdminID()});
        }
    }

}
