/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.mwcrime;

import frame.background_processing.WindowAction;

/**
 *
 * @author PREDATOR
 */
public class Manage_MostWantedCrime extends WindowAction {

    /**
     * Creates new form Manage_MostWantedCrime
     */
    public Manage_MostWantedCrime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbLogoMostWantedCrime = new javax.swing.JLabel();
        txtfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMostWantedCrime = new javax.swing.JTable();
        pnMostWantedCrime = new javax.swing.JPanel();
        lbControlMWTCrime = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbCausesOfDeath = new javax.swing.JLabel();
        lbEvidence = new javax.swing.JLabel();
        txtfFullName = new javax.swing.JTextField();
        txtfHeight = new javax.swing.JTextField();
        txtfIdentification = new javax.swing.JTextField();
        lbDoctorName = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lbEvidence1 = new javax.swing.JLabel();
        txtfWeight = new javax.swing.JTextField();
        lbDoctorName1 = new javax.swing.JLabel();
        lbDoctorName2 = new javax.swing.JLabel();
        lbDoctorName3 = new javax.swing.JLabel();
        txtfDangerLevel = new javax.swing.JTextField();
        lbDoctorName4 = new javax.swing.JLabel();
        txtfRewardAmount = new javax.swing.JTextField();
        txtfAge = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbType = new javax.swing.JComboBox<>();
        btnImage = new javax.swing.JButton();
        btnReturn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 660));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbLogoMostWantedCrime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_manage_mwtcrime.png"))); // NOI18N

        txtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtfSearch.setText("Search");
        txtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSearchActionPerformed(evt);
            }
        });

        tbMostWantedCrime.setBackground(new java.awt.Color(204, 204, 204));
        tbMostWantedCrime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MWTCrime ID", "Full Name", "Age", "Gender", "Height", "Weight", "Identification", "Type", "Image", "Danger Level", "Reward Amount"
            }
        ));
        jScrollPane1.setViewportView(tbMostWantedCrime);

        pnMostWantedCrime.setBackground(new java.awt.Color(204, 204, 204));
        pnMostWantedCrime.setPreferredSize(new java.awt.Dimension(1080, 660));

        lbControlMWTCrime.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbControlMWTCrime.setText("Control Most Wanted Crime");

        lbFullName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbFullName.setText("Full Name");

        lbAge.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbAge.setText("Age");

        lbCausesOfDeath.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCausesOfDeath.setText("Gender");

        lbEvidence.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbEvidence.setText("Height");

        txtfFullName.setBackground(new java.awt.Color(220, 220, 220));

        txtfHeight.setBackground(new java.awt.Color(220, 220, 220));

        txtfIdentification.setBackground(new java.awt.Color(220, 220, 220));

        lbDoctorName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDoctorName.setText("Identification");

        btnReset.setBackground(new java.awt.Color(51, 51, 51));
        btnReset.setForeground(new java.awt.Color(51, 51, 51));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/reset_button.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/delete-button.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 204, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/update_button.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(51, 153, 0));
        btnCreate.setForeground(new java.awt.Color(51, 153, 0));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/create-button.png"))); // NOI18N
        btnCreate.setMaximumSize(new java.awt.Dimension(95, 31));

        lbEvidence1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbEvidence1.setText("Weight");

        txtfWeight.setBackground(new java.awt.Color(220, 220, 220));

        lbDoctorName1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDoctorName1.setText("Type");

        lbDoctorName2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDoctorName2.setText("Image");

        lbDoctorName3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDoctorName3.setText("Danger Level");

        txtfDangerLevel.setBackground(new java.awt.Color(220, 220, 220));

        lbDoctorName4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbDoctorName4.setText("Reward Amount");

        txtfRewardAmount.setBackground(new java.awt.Color(220, 220, 220));

        txtfAge.setBackground(new java.awt.Color(220, 220, 220));
        txtfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAgeActionPerformed(evt);
            }
        });

        cbGender.setBackground(new java.awt.Color(220, 220, 220));
        cbGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        cbType.setBackground(new java.awt.Color(220, 220, 220));
        cbType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corruption", "Counterfeit Currency Or Documents", "Crimes Against Children", "Cyber Crime", "Drug Trafficking", "Environmental Crime", "Financial Crime\t", "Firearms Trafficking", "Human Trafficking", "Illcit Goods", "Killing Crime", "Kidnap Crime" }));

        btnImage.setBackground(new java.awt.Color(220, 220, 220));
        btnImage.setText("Choose File");

        javax.swing.GroupLayout pnMostWantedCrimeLayout = new javax.swing.GroupLayout(pnMostWantedCrime);
        pnMostWantedCrime.setLayout(pnMostWantedCrimeLayout);
        pnMostWantedCrimeLayout.setHorizontalGroup(
            pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMostWantedCrimeLayout.createSequentialGroup()
                        .addComponent(lbFullName)
                        .addGap(30, 30, 30)
                        .addComponent(txtfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCausesOfDeath)
                            .addComponent(lbEvidence)
                            .addComponent(lbEvidence1)
                            .addComponent(lbAge))
                        .addGap(45, 45, 45)
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtfHeight)
                            .addComponent(txtfAge)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                        .addComponent(lbControlMWTCrime)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDoctorName3)
                            .addComponent(lbDoctorName4)
                            .addComponent(lbDoctorName2)
                            .addComponent(lbDoctorName1)
                            .addComponent(lbDoctorName))
                        .addGap(32, 32, 32)
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDangerLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfRewardAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        pnMostWantedCrimeLayout.setVerticalGroup(
            pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbControlMWTCrime)
                .addGap(18, 18, 18)
                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDoctorName)
                            .addComponent(lbFullName)
                            .addComponent(txtfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lbAge))
                            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbType, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDoctorName1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbCausesOfDeath)
                                    .addComponent(lbDoctorName2))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMostWantedCrimeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbGender)
                                    .addComponent(btnImage, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEvidence)
                            .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(lbDoctorName3))
                                .addComponent(txtfHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfDangerLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnMostWantedCrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnMostWantedCrimeLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lbDoctorName4))
                                    .addComponent(txtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfRewardAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMostWantedCrimeLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lbEvidence1)))))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/btn_return.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogoMostWantedCrime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(750, 750, 750))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnMostWantedCrime, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo)
                    .addComponent(btnReturn))
                .addGap(9, 9, 9)
                .addComponent(lbLogoMostWantedCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMostWantedCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_MostWantedCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_MostWantedCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_MostWantedCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_MostWantedCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_MostWantedCrime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbCausesOfDeath;
    private javax.swing.JLabel lbControlMWTCrime;
    private javax.swing.JLabel lbDoctorName;
    private javax.swing.JLabel lbDoctorName1;
    private javax.swing.JLabel lbDoctorName2;
    private javax.swing.JLabel lbDoctorName3;
    private javax.swing.JLabel lbDoctorName4;
    private javax.swing.JLabel lbEvidence;
    private javax.swing.JLabel lbEvidence1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbLogoMostWantedCrime;
    private javax.swing.JPanel pnMostWantedCrime;
    private javax.swing.JTable tbMostWantedCrime;
    private javax.swing.JTextField txtfAge;
    private javax.swing.JTextField txtfDangerLevel;
    private javax.swing.JTextField txtfFullName;
    private javax.swing.JTextField txtfHeight;
    private javax.swing.JTextField txtfIdentification;
    private javax.swing.JTextField txtfRewardAmount;
    private javax.swing.JTextField txtfSearch;
    private javax.swing.JTextField txtfWeight;
    // End of variables declaration//GEN-END:variables
}
