/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.complaint;

import frame.background_processing.WindowAction;

/**
 *
 * @author user
 */
public class Register_Complaint extends WindowAction {

    /**
     * Creates new form Register_Complaint
     */
    public Register_Complaint() {
        initComponents();
        
        cbbYearComplaint.setSelectedItem("2023");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbRegisterComplaint = new javax.swing.JLabel();
        lbSuspectName = new javax.swing.JLabel();
        lbSuspectLocation = new javax.swing.JLabel();
        lbComplaintDate = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        btnSendComplaint = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtSuspectName = new javax.swing.JTextField();
        txtSuspectLocation = new javax.swing.JTextField();
        lbDayComplaint = new javax.swing.JLabel();
        cbbDayComplaint = new javax.swing.JComboBox();
        lbMonthComplaint = new javax.swing.JLabel();
        cbbMonthComplaint = new javax.swing.JComboBox();
        lbYearComplaint = new javax.swing.JLabel();
        cbbYearComplaint = new javax.swing.JComboBox();
        cbbType = new javax.swing.JComboBox();
        txtDescription = new javax.swing.JTextField();
        btnReturn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Register Complaint");

        panel.setBackground(new java.awt.Color(220, 220, 220));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N

        lbRegisterComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo_ register_complaint.png"))); // NOI18N

        lbSuspectName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbSuspectName.setText("Suspect Name");

        lbSuspectLocation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbSuspectLocation.setText("Suspect Location");

        lbComplaintDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbComplaintDate.setText("Complaint Date");

        lbType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbType.setText("Type");

        lbDescription.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbDescription.setText("Description");

        btnSendComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/send_button.png"))); // NOI18N

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/reset_button.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtSuspectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuspectNameActionPerformed(evt);
            }
        });

        txtSuspectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuspectLocationActionPerformed(evt);
            }
        });

        lbDayComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbDayComplaint.setText("Day");

        cbbDayComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        cbbDayComplaint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lbMonthComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbMonthComplaint.setText("Month");

        cbbMonthComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        cbbMonthComplaint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        lbYearComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lbYearComplaint.setText("Year");

        cbbYearComplaint.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        cbbYearComplaint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2022", "2023" }));

        cbbType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Missing person", "Most wanted crime", "Others" }));

        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/btn_return.png"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSuspectLocation)
                    .addComponent(lbComplaintDate)
                    .addComponent(lbSuspectName)
                    .addComponent(lbType)
                    .addComponent(lbDescription))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuspectName, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuspectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lbDayComplaint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbDayComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbMonthComplaint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMonthComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbYearComplaint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbYearComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(lbRegisterComplaint)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSendComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo)
                    .addComponent(btnReturn))
                .addGap(99, 99, 99)
                .addComponent(lbRegisterComplaint)
                .addGap(37, 37, 37)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSuspectName)
                    .addComponent(txtSuspectName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSuspectLocation)
                    .addComponent(txtSuspectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplaintDate)
                    .addComponent(lbDayComplaint)
                    .addComponent(cbbDayComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMonthComplaint)
                    .addComponent(cbbMonthComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbYearComplaint)
                    .addComponent(cbbYearComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbType)
                    .addComponent(cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDescription)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtSuspectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuspectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuspectLocationActionPerformed

    private void txtSuspectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuspectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuspectNameActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Complaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Complaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Complaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Complaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Complaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel btnReturn;
    private javax.swing.JButton btnSendComplaint;
    private javax.swing.JComboBox cbbDayComplaint;
    private javax.swing.JComboBox cbbMonthComplaint;
    private javax.swing.JComboBox cbbType;
    private javax.swing.JComboBox cbbYearComplaint;
    private javax.swing.JLabel lbComplaintDate;
    private javax.swing.JLabel lbDayComplaint;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMonthComplaint;
    private javax.swing.JLabel lbRegisterComplaint;
    private javax.swing.JLabel lbSuspectLocation;
    private javax.swing.JLabel lbSuspectName;
    private javax.swing.JLabel lbType;
    private javax.swing.JLabel lbYearComplaint;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtSuspectLocation;
    private javax.swing.JTextField txtSuspectName;
    // End of variables declaration//GEN-END:variables
}
